#   ___      _ _ _             _
#  / __|__ _| (_) |__ _ _ __ _(_)_ _
# | (__/ _` | | | '_ \ '_/ _` | | ' \
# \___\__,_|_|_|_.__/_| \__,_|_|_||_|

# TEST CONFIG

########################
# MENTAL ROTATION TASK #
########################

[mrt]
#heart = true                        # Heart data params (if true, use default)
events = true                       # Event data params (if true, use default)
performance = true                  # Performance data params (if true, use default)
subjective = true                   # Subjective data params (if true, use default)

# Eye tracking data
[mrt.eye]

    # Preprocessing steps
    [mrt.eye.preprocessing]
    time_col = "timestamp"
    pupil_col = "left_pupil_size"

      [mrt.eye.preprocessing.add_velocity_params]
      shift = 1

      [mrt.eye.preprocessing.clean_missing_data_params]
      to_replace = -1
      value = "NaN"

      [mrt.eye.preprocessing.remove_edge_artifacts_params]
      min_ms = 75
      buffer_ms = 50
      show_plot = false

      [mrt.eye.preprocessing.remove_outliers_params]
      on_col = "velocity"
      n = 3
      show_plot = false

    # Feature calculation steps
    [mrt.eye.features]

    gaze_object_col = "gaze_object"
    groupby_col = "event"

    entropy = true
    absolute_gaze_switches = true
    relative_gaze_switches = true
    absolute_gaze_switches_to = ["MRT_Screen","MRT_Shape"]
    relative_gaze_switches_to = [
        "MRT_Screen",
        "MRT_Shape"
    ]

        [mrt.eye.features.aoi_mapping]
        Display_Screen = "AOI1"

# Heart data (ecg)
[mrt.heart]

    # Preprocessing steps
    [mrt.heart.preprocessing]
    time_col = "timestamp"
    ecg_col = "ecg"

        [mrt.heart.preprocessing.rr_peak_detection_params]
        detector = "engzee"

    # Feature calculation steps
    [mrt.heart.features]
    time_col = "timestamp"
    rr_col = "rr_int"

    time_domain = true
    frequency_domain = true
    nonlinear_domain = true

    detrend = false


################################
# COGNITIVE LOAD TASK (n-back) #
################################

[clt]
#heart = true                        # Heart data params (if true, use default)
events = true                       # Event data params (if true, use default)
performance = true                  # Performance data params (if true, use default)
subjective = true                   # Subjective data params (if true, use default)

# Eye tracking data
[clt.eye]

    # Preprocessing steps
    [clt.eye.preprocessing]
    time_col = "timestamp"
    pupil_col = "left_pupil_size"

      [clt.eye.preprocessing.add_velocity_params]
      shift = 1

      [clt.eye.preprocessing.clean_missing_data_params]
      to_replace = -1
      value = "NaN"

      [clt.eye.preprocessing.remove_edge_artifacts_params]
      min_ms = 75
      buffer_ms = 50
      show_plot = false

      [clt.eye.preprocessing.remove_outliers_params]
      on_col = "velocity"
      n = 3
      show_plot = false

    # Feature calculation steps
    [clt.eye.features]

    gaze_object_col = "gaze_object"
    groupby_col = "event"

    entropy = false
    absolute_gaze_switches = false
    relative_gaze_switches = false
    absolute_gaze_switches_to = false
    relative_gaze_switches_to = false

        [clt.eye.features.aoi_mapping]
        Display_Screen = "AOI1"

# Heart data (ecg)
[clt.heart]

    # Preprocessing steps
    [clt.heart.preprocessing]
    time_col = "timestamp"
    ecg_col = "ecg"

        [clt.heart.preprocessing.rr_peak_detection_params]
        detector = "engzee"

    # Feature calculation steps
    [clt.heart.features]
    time_col = "timestamp"
    rr_col = "rr_int"

    time_domain = true
    frequency_domain = true
    nonlinear_domain = true

    detrend = false

